config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', 
                                    registrations: 'users/registrations'
                                  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :users, only: %i[show]
  resources :boards, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:twitter]

  validates :name, presence: true, on: :update
  validates :email, presence: true, uniqueness: true
  # ユーザー作成(新規登録)の時だけパスワード入力必須にする on: :create をセットで記述。
  validates :password, presence: true, on: :create

  attr_accessor :current_password

  # Twitter認証ログイン用
  # ユーザーの情報があれば探し、無ければ作成する
  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid: auth.uid,
        provider: auth.provider,
        name: auth.info.name,
        username: auth.info.nickname,
        email: User.dummy_email(auth),
        password: Devise.friendly_token[0, 20],
        image: auth.info.image
      )
      user.save!
    end
    current_user = user
  end

  # ダミーのメールアドレスを作成
  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # ログイン済ユーザーのみにアクセスを許可する
  before_action :authenticate_user!, except: %i[index]

  protected

  # :account_update を記述して、新規登録のときは必要ないが、あとからプロフィール充実させるときは許可したいカラム名をここに追記
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name image avatar favorite_player kop_history])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.all.includes(:user).order(created_at: :desc)
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted? # DBに保存済みかどうかを判定
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.valid?
      @user.update(update_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def update_params
    params.require(:user).permit(:name, :image, :avatar, :favorite_player, :kop_history)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return '' if resource.errors.empty?

    html = ''
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/boards/_board.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="board-id-<%= board.id %>">
    <div class="card">
      <%= image_tag 'board_sample.jpeg', class: 'card-img-top', size: '300x200' %>
      <div class="card-body">
        <div class='mr10 float-right'>
          <a href="#"><%= fa_icon 'trash', class: 'pr-1' %></a>
          <a href="#"><%= fa_icon 'pen' %></a>
        </div>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= fa_icon 'user' %>
            <%= board.user.name %>
          </li>
          <li class="list-inline-item">
            <%= fa_icon 'far calendar-alt' %>
            <%= l board.created_at, format: :long %>
          </li>
        </ul>
        <p class="card-text"><%= board.body %></p>
      </div>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-10 offset-lg-1">
      <!-- 検索フォーム -->
      <form>
        <div class="input-group mb-3">
          <input class="form-control" placeholder="検索ワード" type="search" />
          <div class="input-group-append">
            <input type="submit" value="検索" class="btn btn-primary" />
          </div>
        </div>
      </form>
    </div>
  </div>

  <!-- 掲示板一覧 -->
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @boards.present? %>
          <%= render @boards %>
        <% else %>
          <p><%= t('.no_result') %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%= render 'layouts/flash_messages' %>
<div class="main-container">
  <div class="top-title">
    <h1>You'll Never Walk Alone</h1>
  </div>

  <div class="top-inner-text">
    <p>Liverpoolを愛してやまない管理人が</p>
    <p>KOPの皆さんとコミュニティを築き</p>
    <p>互いに情報交換をする事で</p>
    <p>Liverpoolを一緒に盛り上げていきたく開設しました！！</p>
  </div>  
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |msg_type, msg| %>
  <div class="alert alert-<%= msg_type %>" role="alert" id="alert">
    <a href='#' class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YouWillNeverWalkAlone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/header' %>
    <% else %>  
      <%= render 'shared/before_login_header' %>
    <% end %>
    <% if devise_controller? %>
      <div class="container-fluid py-4 mw-md">
      <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
<nav class="navbar navbar-expand navbar-light">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag 'logo.png', size: '65x65' %>
  <% end %>
  <div id="Navber">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to '新規登録', new_user_registration_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'ログイン', new_user_session_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>
</header>

app/views/shared/_footer.html.erb
<footer id='footer' class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <div class="copyright">
          <p>Copyright © 2021. You'll Never Walk Alone</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
<nav class="navbar navbar-expand navbar-light">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= image_tag 'logo.png', size: '65x65' %>
  <% end %>
  <div id="Navber">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'マイページ', user_path(:id), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to '掲示板一覧', boards_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'ログアウト', destroy_user_session_path, class: 'nav-link', method: :delete %>
      </li>
    </ul>
  </div>
</nav>
</header>

app/views/users/show.html.erb
<h2><%= t('.title') %></h2>
<img src=<%= @user.image %>>
<table class="table">
  <tbody>
    <tr>
      <th class="table__col1"><%= User.human_attribute_name('name') %></th>
      <td class="table__col2"><%= @user.name %></td>
    </tr>
    <tr>
      <th class="table__col1"><%= User.human_attribute_name('email') %></th>
      <td class="table__col2"><%= @user.email %></td>
    </tr>
    <tr>
      <th class="table__col1"><%= User.human_attribute_name('favorite_player') %></th>
      <td class="table__col2"><%= @user.favorite_player %></td>
    </tr>
    <tr>
      <th class="table__col1"><%= User.human_attribute_name('kop_history') %></th>
      <td class="table__col2"><%= @user.kop_history %>年</td>
    </tr>
  </tbody>
</table>

# ここに掲示板にした自分の投稿が見られる様に追記する。

<%= link_to t('.edit'), edit_user_registration_path %>